[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Ihor Lukianov <lis05st@gmail.com>"]
license = "MIT OR Apache-2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.release.package.int]
opt-level = "s"
codegen-units = 1
strip = true

[profile.release.package.rv32-isa]
opt-level = "s"


